(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(auto-save-default nil)
 '(blink-matching-paren nil)
 '(c-default-style (quote ((c-mode . "awk") (c++-mode . "awk") (java-mode . "java") (awk-mode . "awk") (other . "gnu"))) t)
 '(compilation-read-command nil)
 '(custom-enabled-themes (quote (wombat)))
 '(default-input-method "russian-computer")
 '(dired-dwim-target t)
 '(dired-recursive-copies (quote always))
 '(ecb-layout-name "left3")
 '(ecb-layout-window-sizes nil)
 '(ecb-options-version "2.40")
 '(ecb-tip-of-the-day nil)
 '(ecb-windows-width 0.25)
 '(global-hl-line-mode nil)
 '(global-semantic-decoration-mode t)
 '(global-semantic-highlight-func-mode t)
 '(global-semantic-idle-completions-mode t nil (semantic/idle))
 '(global-semantic-idle-local-symbol-highlight-mode t nil (semantic/idle))
 '(global-semantic-idle-scheduler-mode t)
 '(global-semantic-idle-summary-mode t)
 '(global-semanticdb-minor-mode t)
 '(inhibit-startup-screen t)
 '(initial-scratch-message "")
 '(make-backup-files nil)
 '(next-screen-context-lines 4)
 '(org-agenda-files (quote ("/media/transcend/org/projects.org")))
 '(org-agenda-prefix-format (quote ((agenda . " %i %-12:c%?-12t% s") (timeline . "  % s") (todo . " %i %-12:c") (tags . " %i %-12:c") (search . " %i %-12:c"))))
 '(org-columns-default-format "\"%25ITEM %TODO %3PRIORITY %7Effort{:} %8CLOCKSUM %TAGS\"")
 '(org-default-notes-file "/media/transcend/org/projects.org")
 '(org-directory "/media/transcend/org/")
 '(org-enforce-todo-dependencies t)
 '(org-fontify-quote-and-verse-blocks t)
 '(org-fontify-whole-heading-line t)
 '(org-global-properties (quote (("Effort_ALL" . "1:00 2:00 3:00 4:00 5:00 6:00 7:00"))))
 '(org-hide-emphasis-markers t)
 '(org-hide-leading-stars t)
 '(org-level-color-stars-only nil)
 '(org-log-done (quote time))
 '(org-log-into-drawer "LOGBOOK")
 '(org-pretty-entities t)
 '(org-src-fontify-natively t)
 '(package-archives (quote (("gnu" . "http://elpa.gnu.org/packages/") ("marmalade" . "http://marmalade-repo.org/packages/"))))
 '(scroll-bar-mode nil)
 '(semantic-decoration-styles (quote (("semantic-decoration-on-includes" . t) ("semantic-decoration-on-protected-members") ("semantic-decoration-on-private-members") ("semantic-tag-boundary" . t))))
 '(semantic-mode t)
 '(show-paren-delay 0.025)
 '(show-paren-mode t)
 '(show-paren-style (quote parenthesis))
 '(sr-speedbar-skip-other-window-p t)
 '(sr-speedbar-width-x 32)
 '(tool-bar-mode nil)
 '(truncate-lines t)
 '(truncate-partial-width-windows nil))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(cursor ((t (:background "gray"))))
 '(ecb-default-highlight-face ((t (:background "SlateBlue4"))))
 '(ecb-history-face ((t (:inherit ecb-default-highlight-face))))
 '(ecb-method-face ((t (:inherit ecb-default-highlight-face))))
 '(ecb-tag-header-face ((t (:background "gray26"))))
 '(font-lock-warning-face ((t (:background "black" :foreground "pink" :bold t))))
 '(highlight ((t (:background "gray20" :foreground "#ffffff" :underline nil))))
 '(hl-line ((t (:background "gray20" :foreground "white smoke"))))
 '(org-block ((t (:inherit shadow))))
 '(org-block-background ((t (:background "black"))))
 '(org-drawer ((t (:foreground "dim gray"))))
 '(org-hide ((t (:foreground "gray14"))))
 '(org-level-1 ((t (:foreground "white smoke" :weight bold :height 1.0))))
 '(org-level-2 ((t (:weight normal))))
 '(org-level-3 ((t nil)))
 '(org-level-4 ((t nil)))
 '(org-level-5 ((t nil)))
 '(org-level-6 ((t nil)))
 '(org-level-7 ((t nil)))
 '(org-level-8 ((t nil)))
 '(org-link ((t nil)))
 '(org-meta-line ((t nil)))
 '(semantic-decoration-on-includes ((t nil)) t)
 '(semantic-decoration-on-unparsed-includes ((t (:background "purple4"))) t)
 '(semantic-highlight-func-current-tag-face ((t (:background "gray8"))))
 '(semantic-tag-boundary-face ((t (:overline "dim gray"))))
 '(show-paren-match ((t (:background "gray14" :foreground "steelblue3")))))
