#!/bin/bash

find . -type f \
     ! -name cscope.out \
     ! -name System.map \
     ! -name '*o.cmd'	\
     ! -name '.tmp_System.map'	\
     ! -name Module.symvers \
     ! -name tags \
     ! -name TAGS \
     -exec grep -nHI -e $@ {} +